name: Continuous Integration

on: [push, pull_request]

jobs:
  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
      - name: Fail if there were link errors
        run: exit ${{ steps.lc.outputs.exit_code }}
